sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

postgresql: &postgresql
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  min_messages: ERROR
  reconnect: false

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "sqlite" %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
